#!/bin/bash
javac -cp contest.jar player43.java Individual.java Mutation.java Recombination.java
jar cmf MainClass.txt submission.jar player43.class Individual.class Mutation.class Recombination.class WholeArithRecombination.class SingleNonUniformMutation.class

# java -jar testrun.jar -submission=player13  -evaluation=SphereEvaluation -seed=0 #hasStructure and isSeparable
# java -jar testrun.jar -submission=player13  -evaluation=BentCigarFunction -seed=0
# java -jar testrun.jar -submission=player13  -evaluation=SchaffersEvaluation -seed=0 # isMultimodal and hasStructure
# java -jar testrun.jar -submission=player13  -evaluation=KatsuuraEvaluation -seed=0 #   isMultimodal


 #COUNTER=10
 #until [  $COUNTER -lt 1 ]; do
     #echo SEED $COUNTER
     #let COUNTER-=1
     #echo BentCigarFunction
     #java -jar testrun.jar -submission=player13  -evaluation=BentCigarFunction -seed=$COUNTER
     #echo SchaffersEvaluation
     #java -jar testrun.jar -submission=player13  -evaluation=SchaffersEvaluation -seed=$COUNTER # isMultimodal and hasStructure
     #echo KatsuuraEvaluation
     #java -jar testrun.jar -submission=player13  -evaluation=KatsuuraEvaluation -seed=$COUNTER #   isMultimodal
 #done



declare -a populationSize=(
"15" "30" "50" "100"
)
declare -a childrenFactor=(
"1" "2" "5" "7" 
)
declare -a startingSigma=(
"10" "5" "4" "3" "2" "1" "0.5" "0.1"
)
declare -a mutationRate=(
"0.9" "0.8" "0.7" "0.1" "0.0001" 
)
declare -a race_limit=(
"1"
)

# {1002} & {40, 8} & {0.1} & {0.01, 1, 1} & {$10^{-6}$} & {1} & {9.999999992} & {190}\\
# {10} & {10, 4} & {0.1} & {1, 1, 1} & {0.001} & {1} & {9.999999994} & {153}\\

#300 , 1.0 , 1.0E-9 , 40 , 1.0E-15 , 4 , 1 , 0


for ps in "${populationSize[@]}"
do
    for cf in "${childrenFactor[@]}"
    do
        for sigma in "${startingSigma[@]}"
        do
            for mutationRate in "${mutationRate[@]}"
            do
                    echo "------------------------------------------------------------------------------------------------------"
                        for race in "${race_limit[@]}"
                        do
                            COUNTER=1
                            until [  $COUNTER -lt 1 ];
                            do
                                let COUNTER-=1
                                #java -Dps=$ps -Dmutchance=$mutchance -Dcf=$cf -DstartingSigma=$sigma -DmutationRate=$mutationRate -Drace=$race -jar testrun.jar -submission=player43  -evaluation=BentCigarFunction -seed=$COUNTER
                                #java -Dps=$ps -Dmutchance=$mutchance -Dcf=$cf -DstartingSigma=$sigma -DmutationRate=$mutationRate -Drace=$race -jar testrun.jar -submission=player43  -evaluation=SchaffersEvaluation -seed=$COUNTER
                                java -Dps=$ps -Dmutchance=$mutchance -Dcf=$cf -DstartingSigma=$sigma -DmutationRate=$mutationRate -Drace=$race -jar testrun.jar -submission=player43  -evaluation=KatsuuraEvaluation -seed=$COUNTER
                            done
                        done
            done
        done
    done

done